module Generator.Common
    ( ProjectRootDir
    , nodeVersion
    , nodeVersionAsText
    ) where

import Text.Printf (printf)


data ProjectRootDir -- ^ Directory where the whole web app project (client, server, ...) is generated.

-- | Node version that node packages generated by this generator expect.
--   (major, minor, patch)
nodeVersion :: (Int, Int, Int)
nodeVersion = (14, 5, 0)

nodeVersionAsText :: String
nodeVersionAsText = printf "v%d.%d.%d" major minor patch
  where (major, minor, patch) = nodeVersion
