rules:
  unpinned-uses:
    config:
      policies:
        # While we don't have an autoupdater, we don't want to pin dependencies
        # to a specific version, or we'd miss out on security updates. This rule
        # will only enforce pinning to major versions.
        "*": ref-pin
