import { readFileSync } from "fs";
import { globSync } from "glob";
import path from "path";

export type DocsSidebars = { [sidebarName: string]: ResolvedSidebarItem[] };

export type ResolvedSidebarItem =
  | ResolvedSidebarLink
  | ResolvedSidebarCategory
  | { type: string; [key: string]: unknown };

export interface ResolvedSidebarLink {
  type: "link";
  href: string;
  label: string;
  docId?: string;
}

export interface ResolvedSidebarCategory {
  type: "category";
  label: string;
  items: ResolvedSidebarItem[];
}

/**
 * Props as in the data we provide to React components.
 * This is the where the data for sidebars lives.
 */
const PROP_FILES_GLOB =
  ".docusaurus/docusaurus-plugin-content-docs/default/p/docs-*.json";

/**
 * Loads the fully resolved sidebars Docusaurus writes during the build, indexed
 * by Wasp version. Unlike the authored `versioned_sidebars/*.json`, these have
 * `autogenerated` blocks already expanded and include every sidebar name (docs,
 * guides, api) with curated labels, order, and hrefs.
 *
 * Requires no stale Docusaurus data to work properly.
 */
export function loadResolvedSidebarsByWaspVersion(
  siteRoot: string,
): Map<string, DocsSidebars> {
  const sidebarsByWaspVersion = new Map<string, DocsSidebars>();
  const sidebarPropsFiles = globSync(PROP_FILES_GLOB, { cwd: siteRoot });

  for (const sidebarPropsFileRelPath of sidebarPropsFiles) {
    const sidebarPropsContent = readFileSync(
      path.join(siteRoot, sidebarPropsFileRelPath),
      "utf8",
    );
    const sidebarProps = JSON.parse(sidebarPropsContent);

    const waspVersion = sidebarProps?.version?.version;
    const docsSidebars = sidebarProps?.version?.docsSidebars;
    if (typeof waspVersion !== "string" || !docsSidebars) {
      throw Error("Sidebar props files glob resolved a stray file.");
    }

    sidebarsByWaspVersion.set(waspVersion, docsSidebars);
  }

  if (sidebarsByWaspVersion.size === 0) {
    throw new Error(
      `No resolved sidebars found at ${PROP_FILES_GLOB}. Run the build first.`,
    );
  }

  return sidebarsByWaspVersion;
}

export function isSidebarCategory(
  item: ResolvedSidebarItem,
): item is ResolvedSidebarCategory {
  return (
    item.type === "category" &&
    Array.isArray((item as ResolvedSidebarCategory).items)
  );
}

export function isSidebarLink(
  item: ResolvedSidebarItem,
): item is ResolvedSidebarLink {
  return (
    item.type === "link" &&
    typeof (item as ResolvedSidebarLink).href === "string"
  );
}
