min_version = "2026.6.11"

[tools]
"github:tfausak/cabal-gild" = "1.5.0.1"
"cabal" = "3.12.1.0"
"ormolu" = "0.7.2.0"

# The `mise-ghcup` plugin declares `aqua:ghcup` as a dependency specifically
# instead of just `ghcup` to avoid conflicts, so we need to declare it like that
# here as well.
"aqua:ghcup" = "0.2.6.1"

# Keep in sync with:
# - /waspc/cabal.project
# - /waspc/dev-tool.project
"mise-ghcup:ghc" = "9.6.7"

# Make sure that this version of HLS has a pre-built binary for the GHC version
# we use above.
"mise-ghcup:hls" = "2.12.0.0"

# This should be equal to Wasp's lowest supported Node version.
# Keep in sync with:
# - The compiler (Wasp.Node.Version).
# - The docs: /docs/introduction/quick-start.md ("Requirements" section).
# - The docs plugin: /web/src/remark/search-and-replace.ts
"node" = "24.14.1"

[plugins]
"vfox:mise-ghcup" = "https://github.com/cprecioso/mise-ghcup.git"

[bootstrap.packages]
# Dependencies for Ubuntu / Debian
# GHCup dependencies (https://www.haskell.org/ghcup/install/reqs/#linux-ubuntu)
"apt:build-essential" = "latest"
"apt:curl" = "latest"
"apt:libffi-dev" = "latest"
"apt:libgmp-dev" = "latest"
"apt:libncurses-dev" = "latest"
# Cabal dependencies
"apt:zlib1g-dev" = "latest"

# Dependencies for Alpine
# GHCup dependencies (https://www.haskell.org/ghcup/install/reqs/#linux-alpine)
"apk:binutils-gold" = "latest"
"apk:curl" = "latest"
"apk:gcc" = "latest"
"apk:g++" = "latest"
"apk:gmp-dev" = "latest"
"apk:gmp-static" = "latest"
"apk:libc-dev" = "latest"
"apk:libffi-dev" = "latest"
"apk:make" = "latest"
"apk:musl-dev" = "latest"
"apk:ncurses-dev" = "latest"
"apk:perl" = "latest"
"apk:pkgconfig" = "latest"
"apk:tar" = "latest"
"apk:xz" = "latest"
# `./run` script dependencies
"apk:bash" = "latest"
# Cabal dependencies
"apk:zlib-dev" = "latest"
"apk:zlib-static" = "latest"
# Prisma dependencies
"apk:openssl" = "latest"

[settings]
lockfile = true
experimental = true # Needed for backend plugins (mise-ghcup) to work.

[settings.node]
# The Node backend has a knack for compiling from source on Alpine even when
# there's a pre-built binary available. So we explicitly tell it not to do that.
compile = false
