min_version = "2026.4.6"

[tools."github:tfausak/cabal-gild"]
version = "1.5.0.1"

[tools."github:tweag/ormolu"]
version = "0.7.2.0"

[tools."github:haskell/ghcup-hs"]
version = "latest"
bin = "ghcup"

[tools."ghcup:cabal"]
version = "3.12.1.0"
depends = "github:haskell/ghcup-hs"

[tools."ghcup:ghc"]
# Keep in sync with:
# - /waspc/cabal.project
# - /waspc/dev-tool.project
version = "9.6.7"
depends = "github:haskell/ghcup-hs"

[tools."ghcup:hls"]
# Make sure that this version of HLS has a pre-built binary for the GHC version
# we use above.
version = "2.12.0.0"
depends = "github:haskell/ghcup-hs"

[tools.node]
# Keep in sync with:
# - The compiler (Wasp.Node.Version).
# - The docs: /docs/introduction/quick-start.md ("Requirements" section).
# - The docs plugin: /web/src/remark/search-and-replace.ts
# - CI files that use Alpine (search for `alpine` in /.github).
version = "22.12.0"

[plugins]
ghcup = "https://github.com/cprecioso/mise-ghcup"

[settings]
lockfile = true
experimental = true
