// This file is auto-generated by Wasp.
// DO NOT EDIT THIS FILE MANUALLY

import { createAuthRequiredPage } from "wasp/client/auth";

import { HomePage as HomePage } from './pages/HomePage'
import { CatchAllPage as CatchAllPage } from './pages/CatchAllPage'
import SignupPage from './features/auth/pages/Signup'
import LoginPage from './features/auth/pages/Login'
import { PasswordReset as PasswordResetPage } from './features/auth/pages/PasswordReset'
import { EmailVerification as EmailVerificationPage } from './features/auth/pages/EmailVerification'
import { RequestPasswordReset as RequestPasswordResetPage } from './features/auth/pages/RequestPasswordReset'
import { ProfilePage as ProfilePage } from './features/auth/pages/ProfilePage'
import { ManualSignupPage as ManualSignupPage } from './features/auth/pages/ManualSignupPage'
import { CustomSignupPage as CustomSignupPage } from './features/auth/pages/CustomSignupPage'
import { TasksPage as TasksPage } from './features/operations/pages/TasksPage'
import { TaskDetailPage as TaskPage } from './features/operations/pages/TaskDetailPage'
import { SerializationPage as SerializationPage } from './features/operations/pages/SerializationPage'
import { JobsPage as JobsPage } from './features/jobs/pages/JobsPage'
import { ApisPage as ApisPage } from './features/apis/pages/ApisPage'
import { ListPage as CrudList } from './features/crud/pages/ListPage'
import { DetailPage as CrudDetail } from './features/crud/pages/DetailPage'
import { StreamingTestPage as StreamingPage } from './features/streaming/pages/StreamingTestPage'
import { ChatPage as ChatPage } from './features/chat/pages/ChatPage'

export const routes = {
  HomeRoute: HomePage,
  CatchAllRoute: CatchAllPage,
  SignupRoute: SignupPage,
  LoginRoute: LoginPage,
  PasswordResetRoute: PasswordResetPage,
  EmailVerificationRoute: EmailVerificationPage,
  RequestPasswordResetRoute: RequestPasswordResetPage,
  ProfileRoute: createAuthRequiredPage(ProfilePage),
  ManualSignupRoute: ManualSignupPage,
  CustomSignupRoute: CustomSignupPage,
  TasksRoute: createAuthRequiredPage(TasksPage),
  TaskRoute: createAuthRequiredPage(TaskPage),
  SerializationRoute: SerializationPage,
  JobsRoute: createAuthRequiredPage(JobsPage),
  ApisRoute: ApisPage,
  CrudListRoute: createAuthRequiredPage(CrudList),
  CrudDetailRoute: createAuthRequiredPage(CrudDetail),
  StreamingRoute: StreamingPage,
  ChatRoute: createAuthRequiredPage(ChatPage),
} as const;
