- arguments:
  # NOTE: List of extensions below should reflect the list
  #   of default extensions from package.yaml.
  - -XOverloadedStrings
  - -XTemplateHaskell
  - -XQuasiQuotes
  - -XScopedTypeVariables

- ignore: {name: Use camelCase} # We can decide this on our own.
- ignore: {name: Eta reduce} # We can decide this on our own.
- ignore: {name: Use newtype instead of data} # We can decide this on our own.
- ignore: {name: Use $>} # I find it makes code harder to read if enforced.
- ignore: {name: Use list comprehension} # We can decide this on our own.
