# This YAML file describes your package. Stack will automatically generate a
# Cabal file when you run `stack build`. See the hpack website for help with
# this file: <https://github.com/sol/hpack>.
name:                waspc
version:             0.3.0.0 # %WASP_VERSION% - annotation for new-release script.
github:              "Martinsos/waspc"
license:             MIT
author:              "wasp-lang"
maintainer:          "sosic.martin@gmail.com, matija.sosic@gmail.com"
copyright:           "2020 wasp-lang"

# NOTE: If you modify list of default extensions, make sure to also update .hlint.yaml file,
#   specifically `arguments` field, so that it contains these same extensions.
default-extensions:
  - OverloadedStrings
  - TemplateHaskell
  - QuasiQuotes
  - ScopedTypeVariables

extra-source-files:
  - README.md
  - ChangeLog.md

data-dir: data/
data-files:
  - Generator/templates/**/*
  - Cli/bash-completion
  - Cli/templates/**/*

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/Martinsos/waspc#readme>

dependencies:
  - base >= 4.7 && < 5

ghc-options:
  - -Wall
  - -optP-Wno-nonportable-include-path # To avoid warning caused by .../autogen/cabal_macros.h. on OSX.
  # -fwrite-ide-info and -hiedir=.hie tell GHC to write compile-time information about the code
  # to .hie directory. This information can then be used by other tools, e.g. stan (static analyzer).
  - -fwrite-ide-info
  - -hiedir=.hie

build-tools:
  - alex
  - happy

library:
  source-dirs: src
  dependencies:
    - filepath
    - parsec
    - mustache
    - text
    - aeson
    - directory
    - split
    - unordered-containers
    - path
    - time
    - exceptions
    - process
    - conduit
    - conduit-extra
    - async
    - bytestring
    - regex-tdfa
    - utf8-string
    - Glob
    - unliftio
    - array # Used by code generated by Alex for src/Analyzer/Parser/Lexer.x
    - mtl
    - strong-path >= 1.1.2.0
    - template-haskell
    - path-io
    - cryptohash-sha256
    - containers

executables:
  wasp-cli:
    main:                Main.hs
    source-dirs:         cli 
    ghc-options:
      - -threaded
      - -rtsopts
      - -with-rtsopts=-N
    dependencies:
      - waspc
      - filepath
      - path
      - directory
      - mtl
      - exceptions
      - fsnotify
      - async
      - time
      - path-io
      - uuid
      - cryptonite
      - aeson
      - utf8-string
      - http-conduit
      - strong-path

benchmarks:
  waspc-benchmarks:
    main:                Main.hs
    source-dirs:         benchmark
    ghc-options:
      - -threaded
      - -rtsopts
      - -with-rtsopts=-N
    dependencies:
      - waspc
      - criterion

tests:
  waspc-test:
    main:                TastyDiscoverDriver.hs
    source-dirs:         test
    ghc-options:
      - -threaded
      - -rtsopts
      - -with-rtsopts=-N
    dependencies:
      - waspc
      - tasty
      - tasty-hspec
      - tasty-quickcheck
      - tasty-discover
      - QuickCheck
      - aeson
      - filepath
      - text
      - mtl
      - parsec
      - deepseq
      - path
      - unordered-containers
      - strong-path
      - split
