name: Setup Haskell
description: |
  This action sets up a Haskell environment for use in actions by
  adding the GHC and Cabal binaries to the PATH. It also caches
  the GHC and Cabal installations to speed up subsequent runs.

inputs:
  ghc-version:
    description: |
      The version of GHC to install.
    required: false
    default: "8.10.7"

  cabal-version:
    description: |
      The version of Cabal to install.
    required: false
    default: "latest"

runs:
  using: composite

  steps:
    - uses: haskell-actions/setup@v2
      id: setup-haskell
      with:
        ghc-version: ${{ inputs.ghc-version }}
        cabal-version: ${{ inputs.cabal-version }}

    - name: Verify Haskell setup
      shell: bash
      run: |
        ghc --version
        cabal --version

    # Based on the official recipe for Cabal caching:
    # https://github.com/actions/cache/blob/v4.2.3/examples.md#haskell---cabal
    # We don't cache the `dist-newstyle` directory because we build on different runners
    # with mismatching libc versions. Docker images also have different UIDs and
    # permissions that lead to mismatches.
    - name: Cache Cabal dependencies
      uses: actions/cache@v4
      with:
        path: |
          ${{ steps.setup-haskell.outputs.cabal-store }}
        key: |
          cabal-${{ runner.os }}-${{ runner.arch }}-${{ inputs.ghc-version }}-${{ hashFiles('waspc/*.cabal', 'waspc/*.project', 'waspc/*.project.freeze') }}
        restore-keys: |
          cabal-${{ runner.os }}-${{ runner.arch }}-${{ inputs.ghc-version }}-${{ hashFiles('waspc/*.cabal', 'waspc/*.project', 'waspc/*.project.freeze') }}
          cabal-${{ runner.os }}-${{ runner.arch }}-${{ inputs.ghc-version }}-
