{{={= =}=}}
// This file is auto-generated by Wasp.
// DO NOT EDIT THIS FILE MANUALLY

import { createAuthRequiredPage } from "wasp/client/auth";

{=# pages =}
{=& importStatement =}
{=/ pages =}

export const routes = {
  {=# routes =}
  {= name =}: {= targetComponent =},
  {=/ routes =}
} as const;
