module Wasp.Generator.SdkGenerator.Server.VitePluginG (genServerVitePlugins) where

import Data.Aeson (object, (.=))
import Data.Maybe (fromJust)
import StrongPath (Dir, File', Path', Rel, relfile, (</>))
import qualified StrongPath as SP
import Wasp.AppSpec (AppSpec)
import Wasp.Generator.FileDraft (FileDraft)
import Wasp.Generator.Monad (Generator)
import qualified Wasp.Generator.SdkGenerator.Common as C
import Wasp.Generator.SdkGenerator.Server.VitePlugin.VirtualUserModulesPluginG (genVirtualUserModulesPlugin)
import qualified Wasp.Generator.ServerGenerator.Common as Server
import Wasp.Generator.ServerGenerator.Db.Seed (getDbSeeds)
import Wasp.Project.Common
  ( WaspProjectDir,
    generatedAppDirInWaspProjectDir,
    srcDirInWaspProjectDir,
  )

-- | Vite plugins declaring and supporting the `server` environment, i.e. the
-- environment Wasp bundles the server with.
genServerVitePlugins :: AppSpec -> Generator [FileDraft]
genServerVitePlugins spec =
  sequence
    [ genViteIndex,
      genWaspServerConfigPlugin spec,
      genDetectClientImportsPlugin,
      genDevRunnerPlugin,
      genEnvFilePlugin,
      genVirtualUserModulesPlugin spec
    ]

genViteIndex :: Generator FileDraft
genViteIndex = return $ C.mkTmplFd tmplPath
  where
    tmplPath = C.serverViteDirInSdkTemplatesDir </> [relfile|index.ts|]

genWaspServerConfigPlugin :: AppSpec -> Generator FileDraft
genWaspServerConfigPlugin spec = return $ C.mkTmplFdWithData tmplPath tmplData
  where
    tmplPath = C.serverVitePluginsDirInSdkTemplatesDir </> [relfile|waspServerConfig.ts|]
    tmplData =
      object
        [ "sdkPackageName" .= C.sdkPackageName,
          "serverBundleDirPath" .= toPosixDirPath serverBundleDirInWaspProjectDir,
          "serverEntryFilePath" .= toPosixFilePath serverEntryFileInWaspProjectDir,
          "dbSeedEntryFilePath" .= toPosixFilePath dbSeedEntryFileInWaspProjectDir,
          "areDbSeedsDefined" .= areDbSeedsDefined
        ]

    areDbSeedsDefined = maybe False (not . null) $ getDbSeeds spec

genDetectClientImportsPlugin :: Generator FileDraft
genDetectClientImportsPlugin = return $ C.mkTmplFdWithData tmplPath tmplData
  where
    tmplPath = C.serverVitePluginsDirInSdkTemplatesDir </> [relfile|detectClientImports.ts|]
    tmplData = object ["srcDirInWaspProjectDir" .= SP.fromRelDir srcDirInWaspProjectDir]

genDevRunnerPlugin :: Generator FileDraft
genDevRunnerPlugin = return $ C.mkTmplFdWithData tmplPath tmplData
  where
    tmplPath = C.serverVitePluginsDirInSdkTemplatesDir </> [relfile|devRunner.ts|]
    tmplData = object ["serverStartFilePath" .= toPosixFilePath serverStartFileInWaspProjectDir]

genEnvFilePlugin :: Generator FileDraft
genEnvFilePlugin = return $ C.mkTmplFdWithData tmplPath tmplData
  where
    tmplPath = C.serverVitePluginsDirInSdkTemplatesDir </> [relfile|envFile.ts|]
    tmplData = object ["serverEnvFilePath" .= toPosixFilePath serverEnvFileInWaspProjectDir]

serverRootDirInWaspProjectDir :: Path' (Rel WaspProjectDir) (Dir Server.ServerRootDir)
serverRootDirInWaspProjectDir =
  generatedAppDirInWaspProjectDir </> Server.serverRootDirInGeneratedAppDir

serverBundleDirInWaspProjectDir :: Path' (Rel WaspProjectDir) (Dir Server.ServerBundleDir)
serverBundleDirInWaspProjectDir =
  serverRootDirInWaspProjectDir </> Server.serverBundleDirInServerRootDir

serverSrcDirInWaspProjectDir :: Path' (Rel WaspProjectDir) (Dir Server.ServerSrcDir)
serverSrcDirInWaspProjectDir =
  serverRootDirInWaspProjectDir </> Server.serverSrcDirInServerRootDir

-- NOTE: These entry files are generated by "Wasp.Generator.ServerGenerator" and
-- "Wasp.Generator.ServerGenerator.Db.Seed".
serverEntryFileInWaspProjectDir :: Path' (Rel WaspProjectDir) File'
serverEntryFileInWaspProjectDir = serverSrcDirInWaspProjectDir </> [relfile|server.ts|]

dbSeedEntryFileInWaspProjectDir :: Path' (Rel WaspProjectDir) File'
dbSeedEntryFileInWaspProjectDir = serverSrcDirInWaspProjectDir </> [relfile|dbSeed.ts|]

-- | In development the server runs inside the Vite dev server's process, so the
-- dev runner imports the server's startup code instead of its entry file (which
-- expects to own its process).
serverStartFileInWaspProjectDir :: Path' (Rel WaspProjectDir) File'
serverStartFileInWaspProjectDir = serverSrcDirInWaspProjectDir </> [relfile|start.ts|]

serverEnvFileInWaspProjectDir :: Path' (Rel WaspProjectDir) File'
serverEnvFileInWaspProjectDir = serverRootDirInWaspProjectDir </> Server.dotEnvFileInServerRootDir

toPosixDirPath :: Path' (Rel r) (Dir d) -> FilePath
toPosixDirPath = SP.fromRelDirP . fromJust . SP.relDirToPosix

toPosixFilePath :: Path' (Rel r) File' -> FilePath
toPosixFilePath = SP.fromRelFileP . fromJust . SP.relFileToPosix
