import type * as hast from "hast";
import * as hastSelect from "hast-util-select";
import type * as hastToMdast from "hast-util-to-mdast";
import type * as mdast from "mdast";
import type * as mdastDirective from "mdast-util-directive";
import rehypeParse from "rehype-parse";
import rehypeRemark from "rehype-remark";
import remarkDirective from "remark-directive";
import remarkGfm from "remark-gfm";
import remarkStringify from "remark-stringify";
import { unified } from "unified";
import { SKIP, visit } from "unist-util-visit";
import { LlmDocsContext } from "../context";

/**
 * Creates a Docusaurus HTML to markdown processor.
 *
 * Docusaurus renders MDX into HTML with theme-specific wrappers that the default markdown
 * conversion mangles. This processor recognizes them and emits clean markdown.
 */
export function createDocusaurusHtmlToMarkdownProcessor(
  context: LlmDocsContext,
): (html: string) => string {
  const docusaurusHtmlToMarkdownProcessor = unified()
    .use(rehypeParse)
    .use(
      rehypeReduceDocusaurusPageToValidMarkdownContent,
      context.skipElementInMarkdownDocsClass,
    )
    .use(rehypeRemark, {
      handlers: {
        div(state, element: hast.Element) {
          if (hasClass(element, "theme-code-block")) {
            return docusaurusCodeBlockToMdast(element);
          }
          if (hasClass(element, "theme-admonition")) {
            return docusaurusAdmonitionToMdast(state, element);
          }
          if (hasClass(element, "tabs-container")) {
            return docusaurusTabsToMdast(state, element);
          }
          return state.all(element);
        },
      },
    })
    .use(remarkGfm)
    .use(remarkDirective)
    .use(remarkStringify, {
      bullet: "-",
      emphasis: "*",
      strong: "*",
      fence: "`",
      fences: true,
      rule: "-",
      listItemIndent: "one",
    });

  return (html: string) => {
    const markdown = String(
      docusaurusHtmlToMarkdownProcessor.processSync(html),
    ).trim();
    if (!markdown) {
      throw Error(
        "Markdown content is null. Most likely a stray document. Please update the `isValidMarkdownDocsRoute` function.",
      );
    }
    return markdown;
  };
}

/**
 * Reduces the parsed Docusaurus page to just its markdown content container.
 * Drops unnecessary nodes that would otherwise leak into the markdown.
 * E.g., comments.
 */
function rehypeReduceDocusaurusPageToValidMarkdownContent(
  skipElementClass: string,
): (root: hast.Root) => void {
  return (root) => {
    root.children = [findMarkdownContentContainer(root)];

    visit(root, (node, index, parent) => {
      if (!!parent && !!index && isSkippableNode(node, skipElementClass)) {
        parent.children.splice(index, 1);
        return [SKIP, index];
      }
    });
  };
}

/**
 * Docusaurus content lives in different wrappers depending on the page type:
 * - Docs use `.theme-doc-markdown`.
 * - Blog and resource posts use a bare `.markdown` inside the article.
 * - `blog/` and `resources/` index pages use blog schema.
 *
 * The blog schema is set by us in the `BlogLayout` theme component.
 * The rest is generated by Docusaurus core packages.
 */
const MARKDOWN_CONTENT_CONTAINER_SELECTORS = [
  ".theme-doc-markdown",
  "article .markdown",
  'main[itemtype="http://schema.org/Blog"]',
];

/**
 * @throws {Error} If none of the {@link MARKDOWN_CONTENT_CONTAINER_SELECTORS} match.
 */
function findMarkdownContentContainer(root: hast.Root): hast.Element {
  for (const selector of MARKDOWN_CONTENT_CONTAINER_SELECTORS) {
    const markdownContentContainer = hastSelect.select(selector, root);
    if (markdownContentContainer) {
      return markdownContentContainer;
    }
  }
  throw Error(
    "Unable to find content containers for markdown conversion. Maybe the Docusaurus DOM theme changed?",
  );
}

function isSkippableNode(node: hast.Nodes, skipElementClass: string): boolean {
  // React injects empty `<!-- -->` comments around dynamic values.
  if (node.type === "comment") {
    return true;
  }

  if (node.type === "element") {
    /**
     * A hash link is a link that appears next to headings as # symbol on hover.
     * Clicking it changes the URL to include the title as URI fragment.
     * In markdown it creates unnecessary noise, e.g.:
     * ## When to use Wasp[#](https://wasp.sh/docs#when-to-use-wasp).
     */
    const isDocusaurusHeadingHashLink =
      node.tagName === "a" && hasClass(node, "hash-link");
    if (isDocusaurusHeadingHashLink) {
      return true;
    }

    const hasSkipInMarkdownDocsClass = hasClass(node, skipElementClass);
    if (hasSkipInMarkdownDocsClass) {
      return true;
    }
  }

  return false;
}

/**
 * Converts a Docusaurus code block to a Markdown code block.
 *
 * @example
 * Target HTML:
 * ```html
 * <div class="theme-code-block language-ts">
 *   <div class="codeBlockTitle">main.wasp.ts</div>
 *   <pre><code>
 *     <div class="token-line">const x = 1;</div>
 *     <div class="token-line">const y = 2;</div>
 *   </code></pre>
 * </div>
 * ```
 *
 * Generated markdown without this function:
 * ````md
 * main.wasp.ts
 *
 * ```
 * const x = 1;const y = 2;
 * ```
 * ````
 * Generated markdown with this function:
 * ````md
 * ```ts title="main.wasp.ts"
 * const x = 1;
 * const y = 2;
 * ```
 * ````
 */
function docusaurusCodeBlockToMdast(codeBlock: hast.Element): mdast.Code {
  const codeLanguage = detectCodeBlockLanguage(codeBlock);
  const codeTitle = detectCodeBlockTitle(codeBlock);
  const codeText = hastSelect
    .selectAll(".token-line", codeBlock)
    .map((line) => hastTextContent(line))
    .join("\n")
    .replace(/\s+$/, "");

  if (!codeText) {
    throw new Error("Empty or missing code block content.");
  }

  return {
    type: "code",
    lang: codeLanguage ? codeLanguage : undefined,
    meta: codeTitle ? `title="${codeTitle}"` : undefined,
    value: codeText,
  };
}

function detectCodeBlockTitle(codeBlock: hast.Element): string | null {
  const titleEl = hastSelect.select('[class*="codeBlockTitle"]', codeBlock);
  return titleEl ? hastTextContent(titleEl).trim() : null;
}

/**
 * `language-text` means "no language", so we treat it as none.
 */
function detectCodeBlockLanguage(codeBlock: hast.Element): string | null {
  for (const className of getClassNames(codeBlock)) {
    const match = className.match(/^language-(.+)$/);
    if (match && match[1] !== "text") {
      return match[1];
    }
  }
  return null;
}

/**
 * Renders an admonition back as the original MDX directive (`:::tip ... :::`),
 * via a remark-directive container node.
 *
 * @example
 * Target HTML:
 * ```html
 * <div class="theme-admonition theme-admonition-tip">
 *   <div class="admonitionHeading_...">tip</div>
 *   <div class="admonitionContent_..."><p>Be careful here.</p></div>
 * </div>
 * ```
 *
 * Generated markdown without this function:
 * ```md
 * tip
 *
 * Be careful here.
 * ```
 * Generated markdown with this function:
 * ```md
 * :::tip
 * Be careful here.
 * :::
 * ```
 */
function docusaurusAdmonitionToMdast(
  state: hastToMdast.State,
  admonition: hast.Element,
): mdastDirective.ContainerDirective {
  const admonitionType = detectAdmonitionType(admonition);
  const admonitionCustomTitle = detectAdmonitionCustomTitle(admonition);
  const admonitionContentEl = hastSelect.select(
    '[class*="admonitionContent"]',
    admonition,
  );

  if (!admonitionContentEl) {
    throw Error("Empty admonition content.");
  }

  const children = state.all(
    admonitionContentEl,
  ) as mdastDirective.ContainerDirective["children"];

  const hasCustomTitle =
    !!admonitionCustomTitle &&
    admonitionCustomTitle.toLowerCase() !== admonitionType.toLowerCase();
  if (hasCustomTitle) {
    children.unshift({
      type: "paragraph",
      data: { directiveLabel: true },
      children: [{ type: "text", value: admonitionCustomTitle }],
    });
  }

  return {
    type: "containerDirective",
    name: admonitionType,
    children,
  };
}

function detectAdmonitionType(admonition: hast.Element): string {
  for (const className of getClassNames(admonition)) {
    const match = className.match(/^theme-admonition-(.+)$/);
    if (match) {
      return match[1];
    }
  }
  return "note";
}

/**
 * Returns the admonition's custom title (e.g. from `:::note[Gotcha]`) or an
 * empty string when it just uses the default type label.
 */
function detectAdmonitionCustomTitle(admonition: hast.Element): string | null {
  const heading = hastSelect.select('[class*="admonitionHeading"]', admonition);
  return heading ? hastTextContent(heading).trim() : null;
}

/**
 * Converts Docusaurus tabs to markdown.
 * For JavaScript/TypeScript code switcher, we only keep the TypeScript variant.
 *
 * @example
 * Target HTML:
 * ```html
 * <div class="tabs-container">
 *   <ul role="tablist"><li role="tab">JavaScript</li><li role="tab">TypeScript</li></ul>
 *   <div><div role="tabpanel">...JS code...</div><div role="tabpanel">...TS code...</div></div>
 * </div>
 * ```
 *
 * Generated markdown without this function:
 * ````md
 * -   JavaScript
 * -   TypeScript
 *
 * ```
 * const x = 1;
 * ```
 *
 * ```
 * const x: number = 1;
 * ```
 * ````
 * Generated markdown with this function:
 * ````md
 * ```ts
 * const x: number = 1;
 * ```
 * ````
 */
function docusaurusTabsToMdast(
  state: hastToMdast.State,
  tabs: hast.Element,
): mdast.RootContent[] {
  const tabsLabels = hastSelect
    .selectAll('[role="tab"]', tabs)
    .map((tab) => hastTextContent(tab).trim());
  const tabsPanels = hastSelect.selectAll('[role="tabpanel"]', tabs);

  if (tabsLabels.length !== tabsPanels.length) {
    throw Error("Tabs label count does not equal panel count.");
  }
  if (tabsLabels.length < 2) {
    throw Error("Tabs should require at least 2 different tabs..");
  }

  if (isJsTsTabsPair(tabsLabels)) {
    // For JS / TS tabs, we keep only the TypeScript version.
    const normalizedLabels = tabsLabels.map((label) => label.toLowerCase());
    const typescriptIndex = normalizedLabels.indexOf("typescript");
    return state.all(tabsPanels[typescriptIndex]);
  }

  return tabsPanels.flatMap((panel, index): mdast.RootContent[] => [
    {
      type: "paragraph",
      children: [
        {
          type: "strong",
          children: [{ type: "text", value: tabsLabels[index] }],
        },
      ],
    },
    ...state.all(panel),
  ]);
}

/**
 * Whether the tabs are exactly a JavaScript/TypeScript pair.
 */
function isJsTsTabsPair(tabsLabels: string[]): boolean {
  if (tabsLabels.length !== 2) {
    return false;
  }
  const normalizedLabels = tabsLabels.map((label) => label.toLowerCase());
  return (
    normalizedLabels.includes("javascript") &&
    normalizedLabels.includes("typescript")
  );
}

function hasClass(element: hast.Element, className: string): boolean {
  return getClassNames(element).includes(className);
}

function getClassNames(element: hast.Element): string[] {
  const className = element.properties?.className;
  return Array.isArray(className) ? className.map(String) : [];
}

function hastTextContent(node: hast.Nodes): string {
  if (node.type === "text") {
    return node.value;
  }
  if ("children" in node) {
    return node.children.map(hastTextContent).join("");
  }

  throw new Error("Unknown node text content.");
}
