name: Fetch nightly CLI
description: From an outside repo, fetch the latest nightly CLI build from Wasp's CI runs.

inputs:
  branch:
    description: The branch to fetch the nightly build from. Defaults to 'main'.
    required: false
    default: main
  token:
    description: GitHub token to authenticate the request.
    required: false
    default: ${{ github.token }}
  output-dir:
    description: Directory to download the CLI build into. Defaults to the current directory.
    required: false
    default: "."

runs:
  using: composite

  steps:
    - name: Compute artifact names
      uses: ./.github/actions/compute-artifact-names
      id: compute-artifact-names
      with:
        build-name: ${{ runner.os == 'Linux' && 'linux' || 'macos' }}-${{ runner.arch == 'ARM64' && 'aarch64' || 'x86_64' }}

    - name: Get latest successful run ID
      id: get_run_id
      shell: bash
      run: |
        run_id=$(
          gh run list \
            --workflow "$WORKFLOW_NAME" \
            --branch "$BRANCH" \
            --status success \
            --limit 1 \
            --json databaseId \
            --jq '.[0].databaseId'
        )

        if [ -z "$run_id" ]; then
          # Using the ::error:: prefix lets GitHub handle it as a special string, and shows up as a red error in the logs.
          # https://docs.github.com/en/actions/reference/workflows-and-actions/workflow-commands#setting-an-error-message
          echo "::error::No successful workflow runs found for branch '$BRANCH'."
          exit 1
        fi

        echo "run_id=$run_id" >> $GITHUB_OUTPUT
      env:
        GH_REPO: wasp-lang/wasp
        GH_TOKEN: ${{ inputs.token }}
        BRANCH: ${{ inputs.branch }}
        WORKFLOW_NAME:
          # This name must be in sync with the name used in:
          # /.github/workflows/ci.yaml
          "CI"

    - name: Download artifact
      shell: bash
      run: |
        gh run download "$RUN_ID" \
          --name "$ARTIFACT_NAME" \
          --dir "$OUTPUT_DIR"
      env:
        GH_REPO: wasp-lang/wasp
        GH_TOKEN: ${{ inputs.token }}
        RUN_ID: ${{ steps.get_run_id.outputs.run_id }}
        OUTPUT_DIR: ${{ inputs.output-dir }}
        ARTIFACT_NAME: ${{ steps.compute-artifact-names.outputs.artifact-name }}

outputs:
  artifact-path:
    description: "The path to the downloaded artifact directory."
    value: ${{ inputs.output-dir }}/${{ steps.compute-artifact-names.outputs.artifact-name }}
