# fly.toml app configuration file generated for wasp-ai-server on 2023-06-29T19:11:27+02:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "wasp-ai-server"
primary_region = "mad"

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = false
  auto_start_machines = false
  min_machines_running = 1
