{
  "compilerOptions": {
    "allowSyntheticDefaultImports": true,
    "alwaysStrict": true,
    "declaration": true,
    "declarationMap": true,
    "emitDecoratorMetadata": true,
    "esModuleInterop": true,
    "experimentalDecorators": true,
    "forceConsistentCasingInFileNames": true,
    "importHelpers": true,
    "importsNotUsedAsValues": "error",
    "incremental": true,
    "lib": ["esnext"],
    "module": "commonjs",
    "moduleResolution": "node",
    "newLine": "lf",
    "noEmitHelpers": true,
    "noFallthroughCasesInSwitch": true,
    "noImplicitReturns": true,
    "noUnusedLocals": true,
    "noUnusedParameters": true,
    "outDir": "dist",
    "preserveConstEnums": true,
    "pretty": true,
    "rootDir": "src",
    "removeComments": false,
    "resolveJsonModule": true,
    "sourceMap": true,
    "strict": true,
    "target": "ES2021",
    "tsBuildInfoFile": "dist/.tsbuildinfo",
    "useDefineForClassFields": true
  },
  "include": ["src"]
}
