import styles from './SocialButton.module.css'
import '../auth-styles.css'

// Note about using !important with some of the components:
// This is a workaround for CSS generated by Stitches not being specific enough
// and thus being overridden by Tailwind CSS. https://github.com/wasp-lang/wasp/issues/1764
// Long term we want to move away from Stitches and this is an acceptable workaround for now.

// PRIVATE API
export const SocialButton = ({ children, ...props }: React.AnchorHTMLAttributes<HTMLAnchorElement>) => (
  <a className={styles.socialButton} {...props}>
    {children}
  </a>
)
