// Cloudflare Pages Function (runs on every request).
//
// Content negotiation for LLMs: when a client asks for Markdown via the
// `Accept` header, serve the pre-generated `.md` sibling of the requested doc
// page instead of the HTML. The `.md` files themselves are plain static assets
// (generated by scripts/html-to-md), so the explicit `.md` URL suffix works
// without any of this logic; this only adds the header-based path.

interface PagesContext {
  request: Request;
  next: (input?: Request | string, init?: RequestInit) => Promise<Response>;
}

// Routes that have generated `.md` counterparts.
const MARKDOWN_ROUTE_PREFIXES = ["/docs", "/blog", "/resources"];

export const onRequest = async (context: PagesContext): Promise<Response> => {
  const { request, next } = context;

  if (!wantsMarkdown(request)) {
    return next();
  }

  const url = new URL(request.url);
  const markdownPath = toMarkdownAssetPath(url.pathname);
  if (!markdownPath) {
    return next();
  }

  const markdownUrl = new URL(markdownPath, url.origin);
  const markdownResponse = await next(new Request(markdownUrl, request));
  if (!markdownResponse.ok) {
    // No `.md` for this route; fall back to the normal HTML response.
    return next();
  }

  const headers = new Headers(markdownResponse.headers);
  headers.set("content-type", "text/markdown; charset=utf-8");
  return new Response(markdownResponse.body, {
    status: 200,
    headers,
  });
};

function wantsMarkdown(request: Request): boolean {
  if (request.method !== "GET") {
    return false;
  }
  const accept = request.headers.get("Accept") ?? "";
  return accept.includes("text/markdown");
}

// Maps a doc route to its static `.md` asset path. Returns null for routes
// without a Markdown counterpart (homepage, assets, already-`.md` requests).
function toMarkdownAssetPath(pathname: string): string | null {
  if (pathname.endsWith(".md")) {
    return null;
  }
  const normalized = pathname.replace(/\/+$/, "");
  if (!normalized || !isMarkdownRoute(normalized)) {
    return null;
  }
  return normalized + ".md";
}

function isMarkdownRoute(pathname: string): boolean {
  return MARKDOWN_ROUTE_PREFIXES.some(
    (prefix) => pathname === prefix || pathname.startsWith(prefix + "/"),
  );
}
