name: "Automation - Warm caches"

on:
  workflow_dispatch:
  schedule:
    # GitHub evicts unused caches after 7 days, so we run this every 6 days
    - cron: "0 0 */6 * *"

concurrency:
  group: "automation-cache-warm"
  cancel-in-progress: false

jobs:
  warm-cache-ci:
    # We call a top-level workflow here, so it needs many permissions to do its
    # job. The workflow itself is already checked by zizmor too, so we can
    # safely ignore this warning here.
    # zizmor: ignore[excessive-permissions]
    uses: ./.github/workflows/ci.yaml
    secrets:
      # (Same comment as above)
      # zizmor: ignore[secrets-inherit]
      inherit
