name: "Check - Formatting"

on:
  workflow_call:

env:
  WASP_TELEMETRY_DISABLE: 1

permissions:
  contents: read

jobs:
  prettier:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - uses: ./.github/actions/setup-node

      - name: Run Prettier
        run: |
          npm ci
          npm run check:prettier

  ormolu:
    runs-on: ubuntu-latest

    steps:
      - run: |
          git config --global core.autocrlf input
          git config --global core.eol lf

      - uses: actions/checkout@v6

      - name: Set up ormolu
        uses: jdx/mise-action@v4
        with:
          install_args: ormolu

      - name: Run ormolu
        working-directory: waspc
        run: ./run check:ormolu

  cabal-gild:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v6

      - name: Set up cabal-gild
        uses: jdx/mise-action@v4
        with:
          install_args: cabal-gild

      - name: Run cabal-gild
        working-directory: waspc
        run: ./run check:cabal
