name: "Check - Formatting"

on:
  workflow_call:

env:
  WASP_TELEMETRY_DISABLE: 1

permissions:
  contents: read

jobs:
  prettier:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6

      - uses: actions/setup-node@v6
        with:
          cache: "npm"
          node-version-file: .nvmrc

      - name: Run Prettier
        run: |
          npm ci
          npm run check:prettier

  ormolu:
    runs-on: ubuntu-latest

    steps:
      - run: |
          git config --global core.autocrlf input
          git config --global core.eol lf

      - uses: actions/checkout@v6

      - name: Set up mise
        uses: jdx/mise-action@v3
        with:
          # We only need to install mise itself so it can give us the correct
          # ormolu version. For better GH Actions support, we will run ormolu
          # separately using their official action below.
          install: false
          cache: false

      - name: Get ormolu version
        id: get-ormolu-version
        run: echo "ORMOLU_VERSION=$(mise tool ormolu --requested)" >> $GITHUB_OUTPUT

      # `run-ormolu` versions > 15 require ormolu version >= 0.7.5.0
      - uses: haskell-actions/run-ormolu@v15
        with:
          version: ${{ steps.get-ormolu-version.outputs.ORMOLU_VERSION }}

  cabal-gild:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v6

      - name: Set up cabal-gild
        uses: jdx/mise-action@v3
        with:
          # We only need to install cabal-gild.
          install_args: "cabal-gild"
          cache_key_prefix: "mise-cabal-gild"

      - name: Run cabal-gild
        working-directory: waspc
        run: ./run check:cabal
