name: "Test - Starters"

on:
  workflow_call:

env:
  WASP_TELEMETRY_DISABLE: 1

jobs:
  test-starters:
    name: Test starters
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v7
        with:
          persist-credentials: false
      - uses: ./.github/actions/setup-tools

      - uses: ./.github/actions/install-wasp-cli-artifact

      - name: Install node dependencies
        working-directory: waspc/starters-e2e-tests
        run: npm ci

      - name: Prepare wasp-app-runner
        working-directory: wasp-app-runner
        run: npm install && npm run build

      - name: Run starters e2e tests
        working-directory: waspc/starters-e2e-tests
        env:
          WASP_APP_RUNNER_CLI_CMD: ${{ github.workspace }}/wasp-app-runner/bin/index.js
        run: npm run test:dev
