name: "CI"

on:
  push:
    branches:
      - main
      - release

  pull_request:

  workflow_call:
    inputs:
      override-npm-package-version:
        description: >
          If set, overrides the version of npm packages to publish.
          Useful for publishing an RC version.
          Leading 'v' will be stripped if present.
        required: false
        type: string

  workflow_dispatch:
    inputs:
      override-npm-package-version:
        description: >
          If set, overrides the version of npm packages to publish.
          Useful for publishing an RC version.
          Leading 'v' will be stripped if present.
        required: false
        type: string

concurrency:
  group: ci-${{ github.ref }}
  cancel-in-progress: true

# This is a kind of meta-workflow that calls other workflows. It is used to
# orchestrate the CI process. We ignore the zizmor warnings since this workflow
# will call other workflows that each have their own permissions and secrets
# defined, so we don't want to define them here. Each workflow is also checked
# by zizmor separately, so it is moderately safe to ignore the warnings here.

jobs:
  deploy-test: # zizmor: ignore[excessive-permissions]
    needs: waspc-build
    uses: ./.github/workflows/ci-deploy-test.yaml
    secrets: inherit # zizmor: ignore[secrets-inherit]

  waspc-build: # zizmor: ignore[excessive-permissions]
    uses: ./.github/workflows/ci-waspc-build.yaml
    secrets: inherit # zizmor: ignore[secrets-inherit]
