name: Restart Algolia Crawler

on:
  workflow_dispatch:
  pull_request:
    branches:
      - main
  push:
    branches:
      - deploy-web

jobs:
  restart-crawler:
    name: Restart Algolia Crawler
    runs-on: ubuntu-latest
    steps:
      - name: Restart Algolia Crawler
        run: |
          AUTH_TOKEN=$(echo -n "${{ secrets.ALGOLIA_CRAWLER_USER_ID }}:${{ secrets.ALGOLIA_CRAWLER_API_KEY }}" | base64)
          
          curl -X POST \
            -H "Authorization: Basic $AUTH_TOKEN" \
            -H "Content-Type: application/json" \
            -H "User-Agent: algolia_crawler_github_actions/1.0.0" \
            "https://crawler.algolia.com/api/1/crawlers/${{ secrets.ALGOLIA_CRAWLER_ID }}/reindex"
