name: Restart Algolia crawler

on:
  workflow_dispatch:
  # TEMP SO I CAN ACTUALLY TEST THIS!!!
  pull_request:
    branches:
      - main
  push:
    branches:
      - deploy-web

jobs:
  restart-crawler:
    name: Restart Algolia Crawler
    runs-on: ubuntu-latest
    steps:
    - name: Restart Algolia crawler
      run: |
        # Based on Algolia API: https://www.algolia.com/doc/rest-api/crawler/#tag/actions/operation/startReindex
        algolia_authentication_token=$(echo -n "${{ secrets.ALGOLIA_CRAWLER_USER_ID }}:${{ secrets.ALGOLIA_CRAWLER_API_KEY }}" | base64)
        echo -n "Algolia crawler user id: "${{ secrets.ALGOLIA_CRAWLER_USER_ID }}
        echo -n "Algolia crawler API key: "${{ secrets.ALGOLIA_CRAWLER_API_KEY }}
        echo -n "Algolia authentication token: $algolia_authentication_token"
        curl -X POST \
          --http1.1 \
          -H "Authorization: Basic $algolia_authentication_token" \
          -H "Content-Type: application/json" \
          -H "User-Agent: algolia_crawler_github_actions/1.0.0" \
          -d '{}' \
          "https://crawler.algolia.com/api/1/crawlers/${{ secrets.ALGOLIA_CRAWLER_ID }}/reindex"