name: Run headless e2e tests on starter templates

on:
  workflow_call:
  push:
    paths:
      - "waspc/data/Cli/starters/**"
    branches:
      - main
      - release
  pull_request:
    # paths:
    #   - "waspc/data/Cli/starters/**"

env:
  WASP_TELEMETRY_DISABLE: 1

jobs:
  test-wasp-config:
    name: Test wasp-config
    runs-on: ubuntu-22.04
    steps:
      - uses: "actions/checkout@v4"
        with:
          fetch-depth: 0

      - uses: ./.github/actions/setup-haskell
        with:
          ghc-version: "8.10.7"
          cabal-version: "3.10.2.0"
          cabal-project-dir: waspc

      - uses: actions/setup-node@v4
        with:
          node-version: lts/*

      - name: Install Wasp CLI
        working-directory: waspc
        run: |
          ./run install

      - name: Install dependencies
        working-directory: waspc/starters-e2e-tests
        run: |
          npm ci
          npx playwright install --with-deps

      - name: Run headless E2E tests
        working-directory: waspc/starters-e2e-tests
        run: |
          npm run test:dev
